### ISSUE TITLE
Add additional array functions

### ISSUE THREAD

**Issue by CrossEye** [CrossEye/eweda#17]
Add functions like indexOf, push, sort, splice, join, and unshift.

Essentially duplicate the Array.prototype API, at least the non-nullary part of it.  These would of course be curried, and what would be `this` in the Array.prototype API would be the last parameter.

This would allow users to use these functions in points-free expressions.

**Comment by buzzdecafe** [comment]
native splice has a weird API: mutate the array and return an array of the removed elements. i don't wanna do that here.

**Comment by CrossEye** [comment]
I think the mutation parts of the Array API are what we'd keep, skipping
the return values, but of course not actually mutating -- instead returning
a cloned copy with the mutations applied.   Or at least that's my first
thought.

  -- Scott
